apiVersion: v1
kind: ConfigMap
metadata:
  name: areax-core-config
  namespace: default
data:
  APP_SERVER_PORT: "3005"
  JWT_ISSUER: "project_w"
  JWT_AUDIENCE: "project_w"
  ACCESS_TTL: "15m"
  REFRESH_TTL: "30d"
  DATABASE_HOST: "your-db-host"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "areax_core"
  DATABASE_USER: "admin"
  DATABASE_SSL: "true"
  DATABASE_HOST_TWO: "your-db-host-2"
  DATABASE_PORT_TWO: "3306"
  DATABASE_NAME_TWO: "areax_core_2"
  DATABASE_USER_TWO: "admin"
  DATABASE_SSL_TWO: "true"
  MONGO_PORT: "27017"
  MONGO_DATABASE_NAME: "areax_mongo"
  MONGO_USER: "admin"
  APPLICATION_BASE_URL: "https://api.projectw.ai"
  AWS_BUCKET_REGION: "us-east-1"
  AWS_BUCKET_NAME_1: "areax-bucket"
  RABBITMQ_URL: "amqp://localhost"
  RABBITMQ_EXCHANGE: "areax_exchange"
  RABBITMQ_QUEUE_LOGS: "logs_queue"
  RABBITMQ_QUEUE_PROMPTS: "prompts_queue"
  RABBITMQ_ROUTING_KEY_LOGS: "logs_key"
  RABBITMQ_ROUTING_KEY_PROMPT: "prompt_key"
