apiVersion: v1
kind: Secret
metadata:
  name: areax-core-secrets
  namespace: default
type: Opaque
stringData:
  JWT_SECRET: "change-me"
  JWT_REFRESH_SECRET: "change-me"
  DATABASE_PASS: "change-me"
  DATABASE_PASS_TWO: "change-me"
  MONGO_PASS: "change-me"
  GOOGLE_CLIENT_ID: "change-me"
  GOOGLE_CLIENT_SECRET: "change-me"
  FIREBASE_API_KEY: "change-me"
  ADMIN_SDK_PRIVATE_KEY: "change-me"
  MAILER_USERNAME: "change-me"
  MAILER_PASSWORD: "change-me"
  INSTAGRAM_CLIENT_ID: "change-me"
  INSTAGRAM_CLIENT_SECRET: "change-me"
  OPEN_API_KEY: "change-me"
  GEMINI_API_KEY: "change-me"
  AWS_BUCKET_ACCESS_KEY_ID: "change-me"
  AWS_BUCKET_SECRET_ACCESS_KEY: "change-me"
  WHATSAPP_ACCESS_TOKEN: "change-me"
  TIKTOK_CLIENT_KEY: "change-me"
  TIKTOK_CLIENT_SECRET: "change-me"
  BASIC_AUTH_USERNAME: "change-me"
  BASIC_AUTH_PASSWORD: "change-me"
  SENDGRID_API_KEY: "change-me"
  ENCRYPTION_KEY: "change-me"
  FINGERPRINT_KEY: "change-me"
