apiVersion: v1
kind: Service
metadata:
  name: areax-core-service
  namespace: default
spec:
  selector:
    app: areax-core-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
  type: LoadBalancer
